version: "3"
services:
  react-native-docker:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    volumes:
      - '.:/node'
    command: >
        sh -c "npm start"
